package com.aavu.client.domain;
// Generated Jul 18, 2006 12:44:47 PM by Hibernate Tools 3.1.0.beta4

import java.io.Serializable;
import java.util.Date;
import java.util.Iterator;

import org.gwtwidgets.client.util.SimpleDateFormat;

import com.aavu.client.widget.autocompletion.Completable;
import com.google.gwt.user.client.rpc.IsSerializable;




/**
 * Date generated by hbm2java
 */

public class HippoText extends MetaValue implements IsSerializable, Serializable{
	
	public HippoText(){
		setPublicVisible(false);
	}	

	public HippoText(User u,String string) {
		this();
		setValue(string);
	}

	public void setValue(String s){
		setTitle(s);
	}
	public String getValue(){
		return getTitle();
	}

	public boolean mustHaveUniqueName() {
		return false;
	}

	public boolean isEmpty() {
		return getValue().equals("");
	}

}
