package com.aavu.client.domain;
// Generated Jul 18, 2006 12:44:47 PM by Hibernate Tools 3.1.0.beta4

import java.io.Serializable;
import java.util.Date;
import java.util.Iterator;

import org.gwtwidgets.client.util.SimpleDateFormat;

import com.aavu.client.widget.autocompletion.Completable;
import com.google.gwt.user.client.rpc.IsSerializable;




/**
 * Date generated by hbm2java
 */

public class HippoDate extends Topic implements IsSerializable, Serializable{

	private transient static SimpleDateFormat df = new SimpleDateFormat("M/d/yyyy");	
	
	public HippoDate(){
		setPublicVisible(false);
	}	

	public HippoDate(User u, String d) {		
		super(u,d);
		setPublicVisible(false);
	}

	public Date getDate(){
		long longDate = Long.parseLong(getData());
		return new Date(longDate);    
	}
	public void setDate(Date date){
		setData(date.getTime()+"");
		setTitle(df.format(date));
	}

}
