package com.aavu.client.domain;

import com.google.gwt.user.client.rpc.IsSerializable;
import com.google.gwt.user.client.ui.HorizontalPanel;
import com.google.gwt.user.client.ui.Label;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.Widget;



/**
 * Meta generated by hbm2java
 */

public class Meta  implements IsSerializable{


	// Fields    

	private long id;
	/**
	 * The type.
	 */
	private String type;  //MetaType type;
	private String name;
	/**
	 * The tag this meta belongs to
	 */
	private Tag tag;  


	public Meta(){
		this("Text");
	}

	public Meta(String type){
		this.type = type;
	}

	// public abstract Widget getEditorWidget(boolean editable); 
	//  public abstract Widget getWidget(boolean editable);//, MetaValue metaValue);
	public String getType(){
		return type;
	}


	// Property accessors

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	/**       
	 *      * The type.
	 */

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void  setTag(Tag tag){
		this.tag = tag;
	}
	/**       
	 *      * The type of the value
	 */


	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof Meta) ) return false;
		Meta castOther = ( Meta ) other; 

		return ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
		&& ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
		&& ( (this.tag.getName()==castOther.tag.getName()) || ( this.tag.getName()!=null && castOther.tag.getName()!=null && this.tag.getName().equals(castOther.tag.getName()) ) );
	}

	public int hashCode() {
		int result = 17;


		result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
		//result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
		return result;
	}

//	TODO make this more general (use enums in 1.5 or ??)
	public MetaValue getDefaultValue() {
		MetaValue rtn = new MetaText(); //default

		if (type.equalsIgnoreCase("Text"))
			rtn = new MetaText();
		else if (type.equalsIgnoreCase("Date"))
			rtn = new MetaDate();
		else if (type.equalsIgnoreCase("Topic List"))
			rtn = new MetaTopicList();

		return rtn;
	}

}
