package com.aavu.client.domain;

import com.google.gwt.user.client.rpc.IsSerializable;
import com.google.gwt.user.client.ui.Widget;

/**
 * MetaValue generated by hbm2java
 */

public abstract class MetaValue implements IsSerializable{


    // Fields    

     private int id;
     private Topic topic;
     private Meta meta;
     /**
      * The value in its string representation
     */
     private String value;


    // Constructors

    /** default constructor */
    public MetaValue() {
    }

    
    /** full constructor */
    public MetaValue(Topic topic, Meta meta, String value) {
        this.topic = topic;
        this.meta = meta;
        this.value = value;
    }
    

   
    // Property accessors

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public Topic getTopic() {
        return this.topic;
    }
    
    public void setTopic(Topic topic) {
        this.topic = topic;
    }

    public Meta getMeta() {
        return this.meta;
    }
    
    public void setMeta(Meta meta) {
        this.meta = meta;
    }
    /**       
     *      * The value in its string representation
     */

    /*public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }*/
    
    /**
     * Returns widget displaying value, and allowing editing of the value
     */
    public abstract Widget getWidget();
    /**
     * Saves current widget value
     */
    public abstract void save();
    /**
     * Returns string representing type
     */
    public abstract String getType();
    
    protected abstract Object getValue();
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MetaValue) ) return false;
		 MetaValue castOther = ( MetaValue ) other; 
         
		 return ( (this.getValue()==castOther.getValue()) || ( this.getValue()!=null && castOther.getValue()!=null && this.getValue().equals(castOther.getValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         
         
         
         result = 37 * result + ( getValue() == null ? 0 : this.getValue().hashCode() );
         return result;
   }   





}
