package com.aavu.client.domain;
// Generated Jul 18, 2006 12:44:47 PM by Hibernate Tools 3.1.0.beta4

import java.util.Iterator;

import com.aavu.client.domain.generated.AbstractTag;
import com.aavu.client.widget.autocompletion.Completable;
import com.google.gwt.user.client.rpc.IsSerializable;




/**
 * Tag generated by hbm2java
 */

public class Tag  extends AbstractTag implements  Completable, IsSerializable{

	public Tag(){
		setPublicVisible(false);
	}
	
	public String toPrettyString() {
		StringBuffer rtn = new StringBuffer("Tag:\n");
		
		rtn.append("ID "+getId()+" name "+getName()+"\n");
		
		rtn.append("metas: \n");
		for (Iterator iter = getMetas().iterator(); iter.hasNext();) {
			Meta element = (Meta) iter.next();
			rtn.append(" meta: "+element.getId()+" "+element.getName()+" "+element.getType()+"\n");
		}
		
		return rtn.toString();
	}

	public String getCompleteStr() {
		return getName();
	}



}
