package com.aavu.client.domain;
//Generated Jul 18, 2006 12:44:47 PM by Hibernate Tools 3.1.0.beta4

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.aavu.client.domain.generated.AbstractTopic;
import com.google.gwt.user.client.rpc.IsSerializable;


/**
 * TopicGWT generated by hbm2java
 */

public class Topic extends AbstractTopic implements IsSerializable{

	

	public String toString(){
		return getTitle()+" "+getText();
	}


}
