package com.aavu.client.domain;

import java.io.Serializable;

import com.aavu.client.service.Manager;
import com.google.gwt.user.client.ui.Widget;



/**
 * Meta generated by hbm2java
 */

public abstract class Meta extends Topic implements Serializable {


	public abstract Widget getEditorWidget(Topic top, Manager manager);

	public abstract String getType();

	// @Override
	public void accept(TopicVisitor visitor) {
		visitor.visit(this);
	}

	public String getName() {
		return getTitle();
	}

}
