package com.aavu.client.domain;

// Generated Jul 18, 2006 12:44:47 PM by Hibernate Tools 3.1.0.beta4

import java.io.Serializable;



/**
 * Tag generated by hbm2java
 */

public class Tag extends Topic implements Serializable {

	public Tag() {
		super();

	}
}
